.github/workflows/phylum_analyze_pr.yml, .phylum_project, CHANGELOG.md, CONTRIBUTING.md, poetry.lock, pyproject.toml
This PR will enable Phylum analysis for the repository. It will be possible to analyze dependencies from the Python `poetry.lock` file both locally and automatically in CI, using the `phylum-analyze-pr-action` for all pull requests.
Forget about eating dog food. With this change, we will be able to drink our own champagne! 🍾
- Confirmed that the action does run for this branch...but it didn't find any changed lock files
- Can't fully confirm until a change is made to the lock file
Closes #12
=> ci: enable Phylum analysis for this repository 🍾 

.github/workflows/release.yml, CHANGELOG.md, pyproject.toml
The previous GitHub Personal Access Token (PAT) used in the `Release` workflow was created with a short lifetime and from a personal account (@maxrake). This was not sustainable and was replaced by a company controlled bot/service account (@phylum-bot). This account was configured for code signing and vigilant mode. The `Production` deployment environment and `Release` workflow were updated to include the secrets necessary to make use of the code signing to ensure verified commits and tags.
closes #33
- We won't really know if it works until _after_ the PR is merged and a release is attempted
- The commit/PR title is using the `fix` type to trigger a new patch version
- The only documentation left to update is possibly to create an internal Notion page talking about how to refresh the PAT …
=> fix: use `phylum-bot` account instead of a personal account

README.md, docs/gitlab_ci.md, src/phylum/ci/ci_base.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/cli.py, src/phylum/constants.py, src/phylum/init/cli.py
The `phylum` Python package has been updated to offer the ability to analyze lockfile changes within the GitLab CI/CD environment. Merge requests (MRs) can be analyzed and annotated automatically when they include changes to a lockfile.
The core logic and annotation strategy came from existing Phylum implementations:
* The [phylum-dev/phylum-analyze-pr-action](https://github.com/phylum-dev/phylum-analyze-pr-action) repository is the current working implementation for GitHub
* The [phylum-dev/GitLabCI-Phylum-Analyze-MR](https://github.com/phylum-dev/GitLabCI-Phylum-Analyze-MR) repository is the current implementation for GitLab
* The intent was to replicate as much as what was already available...but in an extensible way
* There were a few deviations and licenses taken where it seemed …
=> feat: add support for GitLab CI environment

src/phylum/ci/ci_base.py
The mapping for package results in the verbose json response for an analyze command changed the key names for the CLI v3.4.0 release. `risk_domain` became `domain` and `risk_level` became `severity`.
Closes #40 
- ~[ ] Have you created sufficient tests?~
=> fix: sync package issue key name changes from CLI v3.4.0 release

docs/gitlab_ci.md, src/phylum/ci/ci_base.py, src/phylum/ci/cli.py, src/phylum/ci/common.py, src/phylum/ci/constants.py, src/phylum/common.py, src/phylum/constants.py, src/phylum/init/cli.py
Changes in this PR allow thresholds for the five risk domains to be set individually in several ways. They can be set at the Phylum project level from either the Phylum CLI or the web UI. They can also be set by `phylum-ci` options (e.g., `--vul-threshold`, `--mal-threshold`, etc.). The default is to use the project level setting unless overridden by a value specified by a `phylum-ci` option. A default secure value (100) will be used when neither of these sources are used to set the value.
Additional changes made:
* The command line arguments were split into logical groups to make their usage scenarios more obvious and provide better help output
* A "Requirement Source" column was added to the "failed" Package detail table output in order to better identify whether the risk domain …
=> !feat: default to project settings for risk domain thresholds

CHANGELOG.md, CONTRIBUTING.md, docs/gitlab_ci.md, src/phylum/ci/cli.py
Add single character option for all flags and current "single dash"
arguments. Update documentation to match.
BREAKING CHANGE: The short options for the following arguments changed:
* `--force-analysis` was changed from `-fa` to `-f`
* `--force-install` was changed from `-fi` to `-i`
* `--vul-threshold` was changed from `-vt` to `-u`
* `--mal-threshold` was changed from `-mt` to `-m`
* `--eng-threshold` was changed from `-et` to `-e`
* `--lic-threshold` was changed from `-lt` to `-c`
* `--aut-threshold` was changed from `-at` to `-o`
Closes #56
=> feat!: use a single character for "single dash" options

.dockerignore, .github/workflows/release.yml, .github/workflows/test.yml, CONTRIBUTING.md, Dockerfile, src/phylum/ci/cli.py, src/phylum/init/cli.py
Some of the changes made to complete this issue and resulting improvements:
* The image base layer was switched from one based on Debian to one based on Alpine
* The compressed image size was reduced from 84MB to 35MB
* The expanded image size was reduced from 245MB to 96MB
* The image acquisition process in GitLab was reduced from ~16s to ~9s and the total run time was reduced from ~26s to ~19s
* The Dockerfile now makes use of BuildKit for caching purposes
* It can be used to create images used for layer caching
* It is also making use of a cache type build mount in order to re-use already built wheels
* This cuts the build time for cross compiled builds by ~75% (after the wheels are in the cache)
Additional changes made in this PR, unrelated to issue #48:
* Reformat code examples to …
=> perf: optimize Docker image

CONTRIBUTING.md, README.md, docs/security.md
The security policy comes from the [CLI repo](https://github.com/phylum-dev/cli/blob/main/docs/security.md)...with an addition about supported versions.
Some relevant links/references:
* [`phylum-ci` repo security overview](https://github.com/phylum-dev/phylum-ci/security)
* This will close out one of the last two items there
* [GitHub documentation on how to add a security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository#about-security-policies)
=> docs: add a security policy

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
The Code of Conduct comes straight from the Contributor Covenant.
There is no issue to track this, but it was discussed at the 06 JUN 2022 Integrations team sync and approved by @louislang 
The enforcement section references [engineering@phylum.io](mailto:engineering@phylum.io) as the address to use for reporting. This address is a group one and, while small now, may not remain that way. It might be better in the longer term to create a dedicated account for such reporting. 
Some relevant links/references:
* [`phylum-ci` repo community standards](https://github.com/phylum-dev/phylum-ci/community)
* This will close out the last of the items there, bringing the project to "all checkmarks"
* [GitHub documentation on how to add a Code of …
=> docs: add a Code of Conduct

.github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/test.yml, Dockerfile
* Create a new GitHub workflow for building and pushing Docker images
* Configure it to be triggered by repository dispatch events
* Ensure the `latest` image tag is not created/pushed for pre-releases
* Expose another build arg to the Dockerfile: `CLI_VER`
* Used to optionally specify the Phylum CLI version to install
* Update the Test workflow to make use of BuildKit-enabled layer caching
* The Release and Docker workflows were purposely not updated to match
* Release docker builds should build from scratch to get latest deps
* Refactor throughout
Closes #50
- It won't be possible to truly test this change until the corresponding work in `phylum-dev/cli` is merged to `main`
- https://github.com/phylum-dev/cli/pull/466
=> feat: coordinate phylum-ci Docker image releases with new CLI releases

.github/workflows/docker.yml, .github/workflows/preview.yml, .github/workflows/release.yml
It turns out the following syntax is invalid for a GitHub Actions workflow:
```yaml
if: ! contains(github.ref, 'rc')
if: !contains(github.ref, 'rc')
```
This was discovered after merging the new Docker workflow and [attempting to trigger it](https://github.com/phylum-dev/phylum-ci/actions/runs/2497648487/workflow)
After searching the docs and coming up empty, a [GitHub Community Forum post](https://github.community/t/expression-syntax-for-not-startswith/17040) for this issue (but for `startswith` instead of `contains`) showed the way to go:
```yaml
if: "!contains(github.ref, 'rc')"
if: contains(github.ref, 'rc') != true
```
Closes #50
=> fix: logical prefixed `not` fails GitHub workflow syntax

.github/workflows/docker.yml, .github/workflows/release.yml, README.md, pyproject.toml
The Docker workflow makes use of steps that expect the `phylum-ci`
release version to include the leading `v`, like checking out the repo
and getting the Python wheel from the latest release. This is due to how
the GitHub releases are referenced by the tag name, which includes the
leading `v`. However, the Docker image tags created by both the Release
and Docker workflows expect the version to be provided without the `v`,
based on standard tag formats in use today.
This change ensures the tags are created in the same format, regardless
of how or where the images are built. The format is:
`<phylum-ci version>-CLIv<Phylum CLI version>`
where both version component fields are expected to be semantic version
identifiers *without* a leading `v`.
Some additional formatting and documentation …
=> fix: docker image tags are inconsistent

.github/workflows/phylum_analyze_pr.yml
The individual thresholds were removed since they are set at the project level. Additionally, the `license` threshold was reduced to 20 in the project settings since group accounts do not allow for issue suppression at the moment and there are a handful of false positive issues related to the license risk domain, the lowest of which is reporting as a 20.
Closes #69
- This PR will serve as the "test"...since the action is a required status check for PRs
- Nothing to update
=> ci: update Phylum Analyze PR action to v2

src/phylum/ci/ci_github.py
Adding the `$GITHUB_WORKSPACE` as a safe directory in `git` is necessary to ensure the GitHub Container action will function properly with the git repository checked out on the runner. However, this recommended workaround was applied too late in the class initialization. The parent class sets the instance predicate attribute for `is_lockfile_changed` in the `__init__` method. Therefore, the workaround needs to be applied in the child class *prior* to this.
Closes #72
Testing was performed manually, with a Docker image created from the changes in this PR and pushed to `maxrake/phylum-ci:GHA` on Docker Hub. This test image was used in a throwaway branch for the action, `phylum-dev/phylum-analyze-pr-action@fix_access`, and ultimately used in the test runs to show the error is no longer …
=> fix: detect lockfile changes in GitHub PRs

.github/workflows/issues.yml, CHANGELOG.md
Automatically add issues created in this project to the main project planning board.
- ~[ ] Does this PR have an associated issue?~
- ~[ ] Have you ensured that you have met the expected acceptance criteria?~
- ~[ ] Have you created sufficient tests?~
Be sure to review additional expectations on the [developments standards page](https://www.notion.so/phylum/Development-Standards-and-Expectations-07f01c12f56b4bc099840d6074c92615#15d11ce9c55540cb90d604a4a178ee86).
~What issue(s) does this PR close. Use the `closes #<issueNum>` here.~
=> ci: automatically add issues to main project board

.github/workflows/release.yml, docs/github_actions.md, docs/gitlab_ci.md, docs/integrations_overview.md
The docs have been updated to contain the new readme.com category for "Integrations". They have also been revised to ensure the links will work correctly from either/both GitHub and the Phylum docs portal. Finally, an overview page was created to point to all the other pages.
The new job added to the existing Release workflow was modeled after the one in the `phylum-dev/cli` repo. The organizational secret used for accessing the Readme.com platform was exposed to this repo and is ready for use.
NOTE: It may be easier to review these pages by viewing them [directly in GitHub, from the branch](https://github.com/phylum-dev/phylum-ci/tree/readme_docs/docs).
Closes #75
=> docs: add integration documentation to Phylum docs page

Dockerfile
With the release of CLI v3.7.0, the `aarch64-unknown-linux-musl` platform was added as a newly supported target triple. This platform allows for natively building docker images from the alpine Python base images. This also means that building images on platforms other than `linux/and64` is much faster.
=> perf: allow native Docker image creation

src/phylum/__init__.py, src/phylum/ci/cli.py, src/phylum/constants.py, src/phylum/init/cli.py
This PR takes on two issues and is relevant now that https://github.com/phylum-dev/cli/pull/528 has been merged into the CLI, adding a new supported platform. The next release of the CLI, with this new supported platform, will cause the `phylum-init` script to be out of date. Instead of updating the static collection of supported platforms, this PR will help to ensure the synchronization is maintained for *any* changes going forward. Changes include:
* Check for valid versions by using the GitHub API to compare against actual releases
* Supported target triples programmatically generated based on the results
* Users will be told when the version provided as an option is not valid
* Removed `SUPPORTED_TARGET_TRIPLES` static collection
* Add `--list-releases` and `--list-targets` options
* …
=> feat: check for and list valid versions and targets programmatically in `phylum-init`

.github/dependabot.yml, .github/workflows/poetry_update.yml, poetry.lock
Dependabot is enabled for version alerts and update PR for GitHub Actions, Dockerfile, and major Python package versions. A separate "Poetry Update" workflow is added to handle the rest of the Python package versions. This workflow was modeled after the one in the `phylum-dev/cli` repo (which is for Cargo updates).
A pre-emptive `poetry update` was run and included in this review as well since it hadn't been done in quite some time.
Closes #17
- ~Have you created sufficient tests?~
=> ci: automate dependency updates and version alerts

.github/workflows/poetry_update.yml, CONTRIBUTING.md, poetry.lock, pyproject.toml
It turns out the `GH_RELEASE_PAT` is not the best choice for the `poetry_update` workflow b/c it is exposed as an _environment_ secret...which has rules in place to require a manual review and approval. Since this workflow is expected to run weekly and in an automated manner, it makes more sense to use an organizational secret instead of an environment secret to control the creation of a PR, when there are poetry package updates.
The first attempt at making this change revealed that the `ADD_TO_PROJECT_PAT` had the correct permissions to create the PR and did not require a manual review/approval to use, but it was owned by @louislang directly instead of an organizational account. After working with @louislang, this PAT was changed to be owned by @phylum-bot instead.
The change to the …
=> ci: use org PAT instead of environment PAT

.github/workflows/auto_updates.yml, .pre-commit-config.yaml, .pre-commit-hooks.yaml, CONTRIBUTING.md, README.md, docs/sync/git_precommit.md, docs/sync/integrations_overview.md, poetry.lock, pyproject.toml, src/phylum/ci/ci_base.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/constants.py
The `phylum-ci` script entry point already had most of the code for a `pre-commit` environment. This PR updated that code to account for some edge cases.
The `.pre-commit-hooks.yaml` file was added, with a single hook configuration defined for use in consuming repositories. This is a Python hook and works without any additional system-level dependencies. If the `phylum` CLI binary is installed locally, it will be used. Otherwise, the hook will install it.
There was an attempt to add a second hook which would make use of the `phylumio/phylum-ci` docker image. This proved too difficult to implement without overhauling the way the image is used in regards to entrypoints. The only real loss is for users who may not want to have the `phylum` CLI installed locally and prefer a self-contained …
=> feat: add git pre-commit hook integration

src/phylum/ci/constants.py
The key name returned from a Phylum analysis, as known by an individual
package `riskVectors` mapping, changed from `vulnerability` to
`vulnerabilities` in the latest release of the Phylum API.
This PR accounts for that change, allowing packages with vulnerabilities to once
again show in the CI integration results.
Closes #93
- Tested locally, with @louislang, @kylewillmon, @furi0us333, and @peterjmorgan watching in a screen share to confirm the issue and it's resolution
- No docs to update
=> fix: incorrect vulnerability risk domain package key name

.github/workflows/docker.yml, .github/workflows/release.yml, Dockerfile, docs/sync/gitlab_ci.md
This change will tag and push the `phylum-ci` Docker image to *both* Docker Hub and the GitHub Container Registry (ghcr.io). Hosting the image on ghcr.io will allow the GitHub Action integration to pull the image without any rate limits...and likely much faster as well.
Closes #92
- These changes were tested manually by running the same commands locally, resulting in the package at <https://github.com/phylum-dev/phylum-ci/pkgs/container/phylum-ci>
- A GitHub Org Admin will need to help with this step (CC: @louislang)
=> feat: host `phylum-ci` Docker image on GitHub Container Registry

src/phylum/ci/ci_base.py
Naming things is hard. Keeping names for risk domains consistent across the various places they are referenced is even harder, it appears. There are still some differences in the API response data for the vulnerability/vulnerabilities risk domain. There is also still a difference for `malicious` and `malicious_code`. These differences are accounted for in the `RiskDomain` dataclass, but they were not accounted for in the different locations these names show up in the json response from the CLI:
* project level threshold name
* individual package `riskVectors` name
* domain name for an issue in an individual package
This PR attempts to account for each of the potential names in each of the places they could be referenced.
Closes #98
- [] ~Have you created sufficient tests?~
- Still no …
=> fix: `Issue Summary` data missing for vulnerability domain

.pre-commit-config.yaml, README.md, docs/img/phylum-ci_options.svg, docs/img/phylum-init_options.svg, docs/script_options.md, docs/sync/git_precommit.md, docs/sync/gitlab_ci.md, poetry.lock, pyproject.toml
Actions taken:
* Add initial page and SVG files for script options
* The pre-commit config was also updated, to exclude SVG file types
* Update top-level `README.md` to include the options output
* These are links to the "raw" GitHub content instead of relative links
* Done so that the images will show up correctly on PyPI, Docker Hub, GHCR, etc.
* Point to script options in integration docs 
* Pointing to a page with the latest script options is much nicer to users than telling them to look at the source code directly
* There were also some formatting changes to allow the pages to display better on readme.com
* Add `rich-codex` as a dev dependency
* This is really only a dependency needed for release
* It could also have been left out of the `poetry` dependencies and installed directly …
=> docs: add script options docs with auto updates

.github/workflows/docker.yml, Dockerfile, README.md, docs/release_process.md, docs/sync/git_precommit.md, docs/sync/gitlab_ci.md, src/phylum/constants.py
The basis for this change is due to how the Linux platform support in the CLI was changed from `unknown-linux-musl` to `unknown-linux-gnu` starting with v3.8.0-rc2, changing the artifact names available to download and install in a non-backwards compatible manner. This is also a breaking change in this repository as the `Dockerfile` had to migrate away from one based on a `python:3.10-alpine` base image to one based on `python:3.10-slim-bullseye`. The resulting docker image is ~113MB compressed (up from ~38MB) and ~327MB uncompressed (up from ~106MB). Documentation was also updated to account for the new minimum supported version of the CLI.
Closes #103
BREAKING CHANGE: Versions of the CLI older than v3.8.0-rc2 are no longer possible to install on Linux systems with the `phylum-init` …
=> feat!: provide a Docker image with glibc instead of musl libc

.github/workflows/release.yml, pyproject.toml
The last release showed that the script options documentation auto-
update feature is still broken. Instead of creating an updated SVG
file(s) for the script options, a stack trace was produced as output
instead, with the following error:
`ModuleNotFoundError: No module named 'phylum'`
A fix was attempted with #107 but could not be fully verified until the
release was made. The belief now is that the `python-semantic-release`
package does not provide enough control over running commands with the
`pre_commit_command` option in the config file.
This change attempts to run the command in the release workflow, as it's
own step, *before* the Python semantic-release step. Everything needed
to run the `rich-codex` command exists in the workflow environment at
the point the step is run. The code …
=> fix: script options auto update still can't find package

.github/workflows/release.yml
It is sometimes necessary to allow for re-running the release workflow,
with the same release package version. Specifically for situations
where that package is already published to TestPyPI and that step would
otherwise fail with an `HTTP Error 400: File already exists` error.
Some reasons why re-running the release workflow is useful:
* The step that publishes the package to TestPyPI succeeds but the
following step that verifies the package fails because TestPyPI is
slow to recognize a published package
* This has already been observed
* Any step after publishing to TestPyPI, but before publishing to PyPI
could fail and require a re-run to complete
* This has not been observed...yet
The solution proposed here is to allow the step that accesses the
TestPyPI package to proceed even when …
=> ci: allow for re-running the release workflow

.github/workflows/release.yml
The release workflow step that publishes the package to the TestPyPI
registry should be allowed to continue on error since there are times
when it is expected to fail (e.g., when re-running the workflow). The
following step will still provide the gating function for the package
verification on the TestPyPI registry. That is, if the verification step
fails, the job will still fail.
This is a response to the last PR, #109, which [resulted in an overall
job/workflow failure](https://github.com/phylum-dev/phylum-ci/runs/8000722044?check_suite_focus=true). The `Publish to TestPyPI` step failed (as expected)
and the `Verify the package` step succeeded (as expected), but the
remaining steps were skipped because of the first step failure.
Reference: …
=> ci: allow for TestPyPI publish failures in release

.github/workflows/release.yml
The release workflow needs the current project (`phylum`) to be
installed now that it gets used by the `rich-codex` tool to update the
script options documentation automatically. Making this change may mean
slightly more time is taken to install the project in CI. It may also
affect the Python cache used in the workflow.
This change is expected to fix the errors seen [in the script_options.md](https://github.com/phylum-dev/phylum-ci/blob/v0.13.2/docs/script_options.md)
file, where the `phylum` module is not found.
=> ci: install current project in release workflow

src/phylum/constants.py
It turns out that the proper lockfile to use for the Java maven ecosystem is `effective-pom.xml` instead of `pom.xml`. The CLI parses `effective-pom.xml` files more effectively than `pom.xml`. Documentation has already been updated and this change will ensure that the integrations will work, with less effort, for `mvn` users. It was always possible to be explicit about the lockfile to analyze, but this change will make `effective-pom.xml` a default for Java environments that already have the file...so it won't need to be specified with the `--lockfile` option.
=> feat: change supported maven lockfile to `effective-pom.xml`

.pre-commit-hooks.yaml, src/phylum/ci/ci_base.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/cli.py
This PR is meant to update the `pre-commit` hook so that it works in a more expected manner for users. It will allow for the native multiprocessing that `pre-commit` provides and not cause the hook to fail simply because one or more of the processes spawned by the tool were instantiated with a list of files (staged or not) that does not include the expected dependency lockfile. See issue #114 for more detail.
Closes #114
- Tests still don't exist for this integration
- Manual testing was performed locally to verify each scenario
=> feat: don't require serial processing of pre-commit hook

Dockerfile, src/phylum/ci/ci_base.py, src/phylum/constants.py, src/phylum/init/cli.py
The Dockerfile has been updated to install the `phylum` package in a
Python virtual environment, which is accessible by non-root users of the
image. These changes were inspired by the Python `black` project, which
did basically the same thing: https://github.com/psf/black/pull/3202
The `phylum-init` script was updated to provide a hidden option
for installing the CLI in a globally accessible directory. That option
is meant to be used in very limited circumstances, namely the Dockerfile
for image creation.
The minimum supported CLI version is currently v3.8.0-rc2 and enough
time has passed that CLI versions prior to v2.2.0 are no longer expected
to exist in the wild. That is when the Phylum config and binary paths
changed, to adhere to the XDG Base Directory Spec. This change removes …
=> feat!: allow docker image use for non-root users

LICENSE, README.md, pyproject.toml
The `poetry` metadata in the `pyproject.toml` file for the license comes from <https://python-poetry.org/docs/pyproject/#license>, which says to use the identifiers as specified at the
[SPDX Open Source License Registry](https://spdx.org/licenses/).
Closes #124
=> chore: change license from MIT to GPLv3+

docs/sync/azure_pipelines.md, src/phylum/ci/ci_azure.py
The documentation has been updated to be more clear about how to disable the shallow fetch option. There is also a better error message reminding users that shallow fetch should be disabled, with a link to more information about how to do so.
There is also an effort to provide more detail around Azure token failures. The places where having an Azure Token and having the correct permissions on that token have been updated to provide a more detailed error message when those criteria are not met.
Closes #134
- Tested manually with @furi0us333
=> fix: account for shallow fetch in Azure Pipelines integration

.github/workflows/phylum_analyze_pr.yml, docs/sync/gitlab_ci.md, src/phylum/ci/ci_base.py, src/phylum/ci/ci_gitlab.py
The ability to recognize when operating in the context of a branch pipeline was encapsulated with a class property. This property was only added to the GitLab integration at this time. It may make sense to extract this property up to the base class, if and when additional environments are modified to work in the same way. The logic was updated to account for the differences between branch pipelines and merge request pipelines, with the preference (order of operations) tending towards merge request pipelines. Output from the analysis will be posted to the log file of either pipeline type, but posting a note to the MR will only happen now when operating in a merge request pipeline. Due to this change, it is now no longer required to have a GitLab token available at all times since it is not …
=> feat: support GitLab branch pipelines

src/phylum/ci/ci_base.py, src/phylum/ci/cli.py
This change adds options to specify a project and, optionally, a group to go with that project. The group option is ignored if the project option is not populated.
When the project option is provided, a project will be created, overwriting any existing `.phylum_project` file. If a group is provided, it will also be created. If the provided project and group already exist, they will be used.
Output is provided to inform users about the new options when the integration fails as a result of a missing `.phylum_project` file.
Closes #136
- No automated tests
- Manual tests have been performed locally, with the `CINone` integration
- Additional manual tests with `CIGitLab` (and maybe more?) still need to be performed
Specifying a project and group, neither of which exists (failure expected): …
=> feat: allow for creating projects

README.md, pyproject.toml, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/cli.py, src/phylum/init/cli.py
This change backs out the use of the `shlex` module to quote the parts
of any command line that can possibly come from user supplied input.
Explicit lists of command line arguments are used instead. Every element
of each list is a single string, regardless of whitespace contained
within. This is true for both static string literals and variables,
whether they came from user input or not. Therefore, each element in the
list will be considered a separate token/argument when supplied to a
`subprocess.run` call. Every instance of `subprocess.run` was reviewed
and updated to this new format.
Fixes #143
- No automated tests
- Manual testing was performed to help ensure no regressions
The same sequence of commands as outlined in #143, but this time with no program halt or stack trace displayed: …
=> fix: sanitize user input to guard against possible cmd injection

README.md, docs/script_options.md
During conversations with a potential customer, feedback was provided to say that the top-level README was not clear enough on the use of SVG files to show the current script options help output. That is, they did not realize that the "images" were actually SVG files that, when clicked on and opened in raw form in the browser, would allow for search and copy/paste functionality. This change makes that hint more obvious by using a markdown quote box, with a bold **HINT** preface. Additionally, the hint is added to all the places the SVG files are displayed.
View of the [README in the `hint_hint` branch](https://github.com/phylum-dev/phylum-ci/tree/hint_hint):
---
Showing that search works from the [direct link](https://raw.githubusercontent.com/phylum-dev/phylum-ci/main/docs/img/phylum-init …
=> docs: provide more hints about using the SVG files

.github/workflows/release.yml
GitHub workflow commands `set-state` and `set-output` have been deprecated. The announcement and upgrade details can be found [on their blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). This change makes the suggested upgrade. It won't be fully tested until the next release.
=> ci: stop using deprecated `set-output` workflow command

.github/workflows/auto_updates.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/test.yml, CONTRIBUTING.md, Dockerfile, README.md, poetry.lock, pyproject.toml, tests/unit/test_package_metadata.py, tox.ini
This change coincides with the release of Python 3.11, which happened 24 OCT 2022. Anyone tracking this repository and this change should update their use of `pyenv` locally, to include py3.11.x
A number of changes were made:
* Update the Docker base image version
* Update the CONTRIBUTING documentation
* Include lockfile checks in workflow steps
* This will provide a CI failure if the lockfile does not correspond to the current version of the `pyproject.toml` file
* Failures could indicate a manual or improperly updated lockfile, which could indicate malicious behavior
* Update the testing environments in `tox`, workflows, and unit tests
* Update `pyproject.toml` and generate an updated `poetry.lock` lockfile
* Add a new classifier
* Change from "caret" to specific range notation for …
=> feat: add Python 3.11 support

docs/sync/azure_pipelines.md, src/phylum/ci/cli.py, src/phylum/constants.py, src/phylum/init/cli.py, src/phylum/init/sig.py, tests/functional/test_init.py, tests/unit/test_sig.py
Actions taken:
* Update the `sig` module
* Remove all minisign based signature verification
* Add RSA SHA256 based signature verification
* Change the function names and docstrings to be more generic
* This will allow for future signature method implementation changes
* Raise `SystemExit` exceptions everywhere possible
* Provide a useful error message
* Exit with a non-zero return code
* Do not clutter the output with a stack trace when the issue is known
* Add a functional test
* Update the unit tests
Other actions taken:
* Use the long form option for label
* Starting with CLI v3.12.0, `--label` was added as a long form option to the `analyze` command
* This new form is preferred since it is more descriptive
* The minimum supported version constants were updated to reflect this
* The …
=> feat!: support RSA SHA256 signature verification in `phylum-init`

.github/workflows/docker.yml, src/phylum/ci/ci_github.py, src/phylum/constants.py, src/phylum/init/cli.py
As of 28 November 2022, the GitHub REST API is versioned with a new calver scheme. The recommendation from GitHub is to update all integrations that make use of this API to be explicit about the version in use. This change does just that for the `phylum-ci` repo. Since all the calls work with the same version at this point, a constant was added to allow for a single source for changing to new/different versions in the future.
References:
* [Blog Post](https://github.blog/2022-11-28-to-infinity-and-beyond-enabling-the-future-of-githubs-rest-api-with-api-versioning/)
* ["API Versions" documentation](https://docs.github.com/rest/overview/api-versions)
=> chore: specify GitHub REST API version

src/phylum/ci/ci_base.py, src/phylum/ci/constants.py, src/phylum/ci/git.py
It turns out that the possible risk domain names are mostly the same between how they are referenced between the project and package levels. The list of potential names was getting added to the list of flags, *without* checking for duplicates first. This was corrected by using a set instead of a list for the potential names. Additionally, the difference between `vulnerabilities` and `vulnerability` was confirmed to have been corrected in phylum-dev/api#424 and thus that entry was updated here as well. So, the only remaining difference is between `malicious_code` and `malicious`, which is being tracked with phylum-dev/api#499
Fixes #174
Output from running the command: `poetry run phylum-ci -afl reqs.txt -p delme_repeat_check -u 100 -m 100 -e 100 -c 100 -o 100`
=> fix: issue summary entries repeated in output

.github/workflows/docker.yml, .github/workflows/test.yml, .phylum_project, Dockerfile, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/cli.py, src/phylum/constants.py, src/phylum/github.py, src/phylum/init/cli.py
* Extract GitHub API methods to a new module
* Support GET requests
* Aggregate common values as globals
* Allow for both authenticated and unauthenticated requests
* Provide option to allow making authenticated GitHub API requests
* Allow for higher rate limits by accepting `GITHUB_TOKEN` envvar
* Provide more detailed error reporting around GitHub API requests
* Provide specific guidance for rate limit errors
* Wrap unhandled errors with contextual output instead of stack traces
* Reduce unauthenticated GitHub API calls to the bare minimum
* Avoid calls made by simply viewing command help output
* Use function level caching for static calls
* Change `--phylum-release` option default to use installed version
* Fall back to `latest` when no CLI is already installed
* Add …
=> feat!: improve experience around GitHub rate limiting API requests

.github/workflows/docker.yml, .github/workflows/release.yml
In adding the feature to increase the rate limits for GitHub API calls (#179), a few of the `phylum-ci` repository workflows were updated to take advantage of the fact that the `GITHUB_TOKEN` is already available in those workflows. However, two updates were missed: the release and docker workflows. This change includes them.
=> chore: include `GITHUB_TOKEN` in release workflows for docker builds

docs/sync/gitlab_ci.md
The differences in access tokens was made more clear so that the scope and role are populated correctly, depending on the type of token (personal, project, or group). The ability to support self-hosted installs with internet access was added.
The procedure for setting up a local environment for confirming self-hosted GitLab instances was documented in #188 as a comment there. The result of testing with that setup can be seen in the screenshots below, but it turns out that the integration works without any _code_ changes. There were a few _documentation_ updates that were necessary to make things more clear. This PR reflects those doc updates.
Closes #188
- N/A
Log output from a branch pipeline run where a known bad dependency was added:
---
Comment and log output from a merge request (MR) …
=> docs: update GitLab CI documentation

docs/sync/azure_pipelines.md, docs/sync/bitbucket_pipelines.md, docs/sync/git_precommit.md, docs/sync/gitlab_ci.md, docs/sync/integrations_overview.md, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/cli.py, src/phylum/ci/constants.py
This change adds an integration for the Bitbucket pipelines CI
environment. Specifically, it adds support for the Bitbucket Cloud
ecosystem, which is their CI/CD as a service offering for repositories
hosted at <https://bitbucket.org/>.
This integration detects and handles both branch pipelines and pull
request (PR) pipelines. When in the PR pipeline context, the results
will be written to logs and also as a comment on the PR. PR comments
in Bitbucket do not allow for HTML tags from markdown input and will
display the tags as text instead of a rendered blend of HTML and
Markdown.
It was discovered that not only was Bitbucket affected by the inline
HTML tags, but also the integrations and code paths that do not rely on
posting a PR comment. That included: `pre-commit`, the local use case …
=> feat: add support for Bitbucket Pipelines

.github/dependabot.yml, .github/workflows/auto_updates.yml, .github/workflows/docker.yml, .github/workflows/phylum_analyze_pr.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/test.yml, .phylum_project, docs/sync/bitbucket_pipelines.md
All GitHub actions were pinned to an explicit SHA instead of a tag name/version. Each pin includes a comment about the version it represents, which will be updated automatically by Dependabot at the same time as the pin.
Other changes made in this PR:
* Update Phylum project file to current format
* Format and refactor the auto_updates workflow
* Be more explicit about the Bitbucket token scope access
* This was based on feedback from @furi0us333 after going through the documentation in an actual Bitbucket Pipepines configuration
Closes #202
=> ci: pin workflow actions

.pre-commit-hooks.yaml, CHANGELOG.md, CONTRIBUTING.md, README.md, docs/release_process.md, docs/sync/azure_pipelines.md, docs/sync/bitbucket_pipelines.md, docs/sync/git_precommit.md, docs/sync/github_actions.md, docs/sync/gitlab_ci.md, poetry.lock, pyproject.toml, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/cli.py, src/phylum/ci/common.py, src/phylum/ci/constants.py, src/phylum/ci/git.py, src/phylum/ci/lockfile.py, src/phylum/constants.py, tests/unit/test_git.py
Actions taken include:
* Add support for multiple lockfiles
* Bump the minimum required Phylum CLI version to v4.5.0
* Ability to specify multiple lockfiles was added then
* Create a `Lockfile` class to represent a single lockfile
* Move properties of a lockfile from `CIBase` to `Lockfile` class
* Update each CI environment to update every lockfile's change status
* Consolidate initialization/instantiation logic in class properties
* The Phylum project name
* Generate a deterministic project name when not otherwise provided
* The Phylum group name
* The lockfile(s) in use
* Detect the lockfile(s) when not otherwise provided
* The Phylum CLI path
* Lockfile hash object
* Move "ensure a project" function from cli to a `CIBase` class method
* Remove pre-requisite check for `.phylum_project` …
=> feat!: allow `.phylum_project` file to be optional

.github/workflows/test.yml, .pre-commit-config.yaml, CONTRIBUTING.md, README.md, poetry.lock, pyproject.toml, src/phylum/__init__.py, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/cli.py, tests/unit/test_package_metadata.py, tox.ini
This PR is about three months early...at least based on the EOL date in [the Python Developer's Guide](https://devguide.python.org/versions/)...but should not be a big deal. This change was made now to help pave the way for some upcoming QA work (type checking, linting, etc.). Changes made include:
* Upgrade `pyupgrade` pre-commit hook
* Update `pyproject.toml` and regenerate `poetry.lock` 
* Uses of `backports.cached_property` were replaced with the standard lib `functools.cached_property`
* Use standard lib `importlib.metadata`
* This replaces the backported `importlib_metadata` package
* Use `shlex.join()` function
* The `shlex.join()` function was introduced in Python 3.8 and returns a
shell-escaped string from a split command
* It is used to protect against injection vulnerabilities …
=> chore!: drop Python 3.7 support

src/phylum/constants.py
Add support for SPDX file types in the supported lockfiles in `phylum-ci`.
```console
../phylum-ci  8  21 on  detect_spdx [✘!?] is 📦 v0.25.0 via 🐍 v3.11.2
❯ cp ../localdev/cli/tests/fixtures/spdx-2.* delme/
../phylum-ci  8  21 on  detect_spdx [✘!?] is 📦 v0.25.0 via 🐍 v3.11.2
❯ l delme
total 12824
drwxr-xr-x   8 maxrake  staff   256B Apr  4 15:41 .
drwxr-xr-x  32 maxrake  staff   1.0K Apr  4 15:40 ..
-rw-r--r--   1 maxrake  staff     0B Mar 13 11:59 empty.txt
-rw-r--r--   1 maxrake  staff   192B Mar 22 17:22 requirements.txt
-rw-r--r--   1 maxrake  staff   2.5M Apr  4 15:41 spdx-2.2.spdx
-rw-r--r--   1 maxrake  staff    10K Apr  4 15:41 spdx-2.2.spdx.json
-rw-r--r--   1 maxrake  staff   3.7M Apr  4 15:41 spdx-2.3.spdx.json
-rw-r--r--   1 maxrake  staff    16K Apr  4 15:41 …
```
=> feat: detect SPDX formatted SBOM files

.github/workflows/test.yml, CONTRIBUTING.md, poetry.lock, pyproject.toml, src/phylum/ci/cli.py, src/phylum/ci/constants.py, tox.ini
This change adds a new `QA` job to the existing `Test` workflow. It is done in a way that the `Test rollup` job can continue to be an enforced status check, but with the addition of this job. A new optional `tox` test environment named `qa` was added and is called by the `QA` job. The environment can also be called by users locally. It relies on simply running `pre-commit` on the existing hooks defined in the repository:
* trim trailing whitespace
* fix end of files
* check yaml
* check for added large files
* `black`
* `pyupgrade`
* analyze lockfile with `phylum-ci`
* This one is skipped
The `phylum-ci` pre-commit hook is skipped in the `QA` job since:
* The current GitHub integration expects to *only* run in a PR context
* The `Test` workflow also includes `workflow_dispatch` and `push` …
=> chore: add QA checks to `Test` workflow

.pre-commit-config.yaml, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/init/cli.py, tests/constants.py
This change adds `refurb` to the QA checks and updates the code to adhere to it's findings. From the [refurb README](https://github.com/dosisod/refurb#why-does-this-exist), the tool is "heavily inspired by clippy, the built-in linter for Rust."
The defaults are used, except for specifying the minimum supported Python version (currently 3.8) so that changes won't be suggested that only exist in newer versions of Python. Additionally, the format when using the pre-commit hook is set to `github`. Even though this is slightly harder to parse when running the hook locally, the benefit outweighs that cost in the way annotations will be added to PRs:
=> ci: add `refurb` pre-commit hook

Dockerfile, src/phylum/ci/ci_base.py, src/phylum/ci/cli.py, src/phylum/constants.py, src/phylum/init/cli.py
This change adds the ability to specify the URI of a Phylum API
instance to use. It does this by adding options to both the `phylum-ci`
and `phylum-init` entrypoint scripts. It also allows for specifying the
option's value by setting the `PHYLUM_API_URI` environment variable. The
value specified with the option takes precedence when both are provided.
When not specified, the CLI will use the default value for the
PRODUCTION instance for new installs and the existing value in the
Phylum settings file, when available, for updated installs.
The Dockerfile was also updated to take advantage of this feature by
adding an optional build argument.
For example, specify 'https://api.staging.phylum.io/' as an option or
envvar to point to the STAGING instance. Regardless of the instance
selected, …
=> feat!: provide ability to specify Phylum API URI

poetry.lock, pyproject.toml, src/phylum/ci/ci_base.py, src/phylum/console.py
With the change to policy based operation, the analysis report is no longer generated within `phylum-ci`. Instead it comes from the `report` element of the "evaluate policy" endpoint offered by the API. This report includes a link to view the project in the Phylum UI. The link is often longer than the width of the terminal used in some CI environments which causes the link to get "clipped" and therefore no longer functional as a clickable URL. This is a regression of issue #140, which was previously fixed in #186.
This change removes the `connect-markdown-renderer` dependency and adds `rich` as a main dependency. `connect-markdown-renderer` was chosen before because it extends the markdown rendering functionality provided by `rich` to include additional elements like tables. The new …
=> fix: link to Phylum UI project clipped in logs

.pre-commit-config.yaml, pyproject.toml, src/phylum/ci/common.py
This change adds `vulture` to the QA checks and updates the code to adhere to it's findings. From the [`vulture`
README](https://github.com/jendrikseipp/vulture), the tool "finds unused code in Python programs."
The defaults are used and the tool is run against the `src` and `tests` directories. This tool was used during the recent major refactoring effort in which the switch away from thresholds and towards policies was made. There was a lot of deleted code and the tool made it very easy to identify the remaining dead code.
=> ci: add `vulture` pre-commit hook

.gitattributes, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/test.yml, .pre-commit-config.yaml, README.md, poetry.lock, pyproject.toml, tests/unit/test_package_metadata.py
This PR is meant to be merged...but only after some changes are made to the lockfile. It is being used to demonstrate an attack where the lockfile is updated surreptitiously and the changes are attempted to be approved through a PR, due to the way GitHub's `linguist` library hides/collapses known lockfiles.
The real changes made here include:
* Add a Discord shield to the README
* Add lockfile refresh steps to workflows
* A `poetry lock --no-update` command is added to all the workflows where `poetry` is used to install an environment from the lockfile
* Doing so "refreshes" the lockfile and will remove any entries in the lockfile that are not actually dependencies of packages defined in the `pyproject.toml` file
* It does not produce an error or non-zero return code when changes are …
=> ci: protect against surreptitious lockfile changes

.github/workflows/test.yml, .pre-commit-config.yaml, CONTRIBUTING.md, README.md, pyproject.toml, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/cli.py, src/phylum/ci/common.py, src/phylum/ci/git.py, src/phylum/ci/lockfile.py, src/phylum/constants.py, src/phylum/github.py, src/phylum/init/cli.py, src/phylum/init/sig.py, tests/__init__.py, tests/functional/__init__.py, tests/functional/test_ci.py, tests/functional/test_init.py, tests/unit/__init__.py, tests/unit/test_git.py, tests/unit/test_package_metadata.py, tests/unit/test_sig.py
`ruff` is the hot new linter for Python. It is written in Rust and is extremely fast. It also has tremendous support and constant updates. It replaces some of the existing (`pyupgrade`) and planned (e.g., `bandit`, `flake8`, `isort`, and `pylint`) QA tools that are outlined in #14. More new rules are added all the time. The initial configuration enables `ALL` rules by default and then selectively ignores specific rules based on conflicts, preference, and existing issues in the backlog.
Using `ALL` has the risk that new rules may be enabled when `ruff` is updated but updates are automated, with a PR that includes enforced QA checks, to weekly dependency and pre-commit hook bumps. Therefore, the real risk is that a developer on this project may have a local version of `ruff` installed that …
=> chore: add `ruff` to QA checks

src/phylum/constants.py
This change is meant to be a stop-gap until #244 replaces the `phylum-ci` implementation of automatic lockfile detection. However, that issue is going to also add manifest support...which requires more research, planning, coordination, and time.
Closes #234
=> feat: add `npm-shrinkwrap.json` and `requirements*.txt` to supported lockfiles

.github/workflows/auto_updates.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/test.yml, .pre-commit-config.yaml, pyproject.toml
The latest release of `ruff` added new rules:
https://github.com/charliermarsh/ruff/releases/tag/v0.0.271. Most of the rules did not hit on any of the existing code. A new ruleset, `flake8-fixme`, was added and it directly conflicts with another ruleset, `flake8-todos`. `flake8-todos` is preferred because it allows for TODO/FIXME/XXX comments in code...so long as they are formatted in a particular way. `flake8-fixme` does not allow for these statements at all. The configuration was updated to ignore the conflicting `flake8-fixme` rules.
A few more `pre-commit` hooks were added and the revision for the `ruff` hook was updated to match the latest release.
Running the `poetry-check` hook locally revealed a gap in coverage. The hook failed because the local cache of packages did not match the …
=> ci: update QA configuration

.github/workflows/test.yml, .pre-commit-config.yaml, pyproject.toml
The changes in #257 introduced an error with the `no-commit-to-branch` pre-commit hook. It causes failures in CI when merging a PR back to `main`. The hook is now skipped in CI to avoid that error. This is acceptable because the hook is meant to be used locally, where blocking a commit before the code can get to the point of running in CI is the goal.
The update to conform to `ruff` release v0.0.271 is also adjusted here. That project realized that the `T` rule prefix for the `flake8-fixme` rules was overloading the `TD` and `T20` rule prefixes. A new release - https://github.com/astral-sh/ruff/releases/tag/v0.0.272 - came out a day later and changed the prefix from `T` to `FIX`. The pre-commit hook and configuration were updated to account for this release.
=> ci: update and fix QA configuration

src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/constants.py, src/phylum/exts/__init__.py, src/phylum/exts/ci/PhylumExt.toml, src/phylum/exts/ci/__init__.py, src/phylum/exts/ci/main.ts
This change starts the shift away from `phylum analyze` commands in favor of using a custom Phylum CLI extension to provide analysis results. The extension is not installed because doing so would not work for all CI environments, namely those that create containers from the Docker image with a non-root user that expects to access the extension files installed by the root user.
Instead of dis-allowing all CLI installs for versions prior to v5.3.1-rc2, this change "straddles" both modes of generating a Phylum analysis: the `phylum analyze` call from CLI releases prior to v5.3.1-rc1 and the use of the new custom extension for CLI releases >= v5.3.1-rc2.
Changes made include:
* Add a new `phylum.exts` sub-package to hold custom CLI extensions
* Add a new `phylum.exts.ci` sub-package to hold …
=> feat: update the phylum analysis technique

src/phylum/constants.py
Closes #235
Closes #270
BREAKING CHANGE: CLI installs prior to v5.5.0 are no longer supported. A Phylum CLI version with ability to parse `pnpm-lock.yaml` and `packages.lock.json` lockfiles is needed.
=> feat!: Add `pnpm-lock.yaml` and `packages.lock.json` lockfile support

src/phylum/ci/common.py, tests/unit/test_lockfile_parse.py
Updates the package descriptor with an additional `lockfile` field.
Closes #279
=> chore: add `lockfile` to PackageDescriptor

src/phylum/constants.py
This change adds the ability to automatically detect `packages.*.lock.json` lockfiles. The minimum required CLI version did not need to change because CLI v5.5.0 was already capable of _parsing_ these lockfiles.
=> feat: add `packages.*.lock.json` lockfile detection

src/phylum/ci/ci_gitlab.py, src/phylum/ci/git.py, tests/unit/test_git.py
This change adds a `git` helper function named `git_fetch` which does what it says. The GitLab integration is updated to be more robust when determining the common ancestor commit. If the default remote branch is not available, which can happen for self-hosted instances of GitLab, the branch is fetched before attempting to use it in a `git merge-base` command.
Closes #289
The code in this PR was tested by making the Docker image `maxrake/phylum-ci:gitlab_fetch` and using this script in a branch's `.gitlab-ci.yml` file:
```
script:
- |
env
rm .git/refs/remotes/origin/main || true
ls -alh .git/refs/remotes/origin || true
phylum-ci || true
ls -alh .git/refs/remotes/origin || true
```
...which produced the following output:
=> feat: improve GitLab integration for partial checkouts

.pre-commit-config.yaml, src/phylum/ci/ci_base.py, src/phylum/logger.py
The latest release of `ruff` added a new rule that would cause CI to fail. It is `subprocess-run-without-check` (PLW1510) and is part of the effort to convert `pylint` rules to `ruff`. Even though `pylint` is not enforced on this repository, there was a disable message to prevent local use of it from firing. Ruff has come a long way and the last remaining vestiges of `pylint` have been removed from this repo. Long live Ruff!
The pre-commit hooks and ignore directives were updated now, in anticipation of the next weekly dependency bump so that one will be more likely to pass CI.
=> build: update pre-commit hooks

src/phylum/ci/ci_gitlab.py, src/phylum/ci/git.py, tests/unit/test_git.py
This change creates a new predicate function named `git_branch_exists` that makes use of the `git show-ref` command, with a specific syntax meant for checking whether a specific branch exists (See the reference command documentation: https://git-scm.com/docs/git-show-ref). This allows the GitLab CI integration to get away from using git internals directly.
The code in this PR was tested by making the Docker image `maxrake/phylum-ci:git_branch_exists` and using this script in a branch's `.gitlab-ci.yml` file:
```
script:
- |
env
rm .git/refs/remotes/origin/main || true
ls -alh .git/refs/remotes/origin || true
phylum-ci || true
ls -alh .git/refs/remotes/origin || true
```
...which produced the following output:
=> refactor: use git command to check branch exists

README.md, src/phylum/constants.py
This change also updates a shield in the README to a new URL so it will continue to show instead of a broken link.
BREAKING CHANGE: CLI installs prior to v5.7.0 are no longer supported. A Phylum CLI version with ability to parse CycloneDX lockfiles is needed.
=> feat!: add CycloneDX lockfile support

src/phylum/ci/common.py
This change fixes a problem where _any_ change in a lockfile results in the finding that _all_ dependencies from the lockfile are new. This was introduced in #282, when the `PackageDescriptor` dataclass added the `lockfile` attribute.
The issue is that the `Lockfile` class uses the `PackageDescriptor` dataclass to make comparisons and compute unique sets of dependencies. The `get_previous_lockfile_packages` function works by writing the previous lockfile object to a temporary file and then parsing that file with the `phylum parse` command. The temporary file will never have the same name as the current lockfile and so the `lockfile` attribute will be different for _all_ dependencies in the given lockfile.
Making this change ensures the `lockfile` attribute of the dataclass is not included …
=> fix: incorrect new dependency logic

pyproject.toml, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/cli.py, src/phylum/github.py, src/phylum/init/cli.py
This change affects all integrations that deal with comments/notes on
PRs/MRs. Previously, these integrations would not account for the
possibility that Phylum-generated comments already exist on the PR/MR.
That led to situations where a FAILED comment was the last one posted
even though actions (commits) were taken to rectify the bad dependencies.
This gap was enabled because the "changed" lockfile looks no different
than the one it is being compared to (e.g., the default branch). The
additional effect of this behavior was that the integration would bail
early and an analysis would therefore not be submitted, leaving the
project in an old/bad/incorrect state when viewed on that label.
The change here is to ensure previous Phylum-generated comments *are*
taken into account. If any are …
=> fix: integrations should check for previous comments

src/phylum/ci/cli.py
This change provides more help and log output to help understand how manifest files are treated and how they should be submitted.
=> docs: add more detail for manifest file support

Dockerfile
Recently, the Docker image creation started generating a warning when attempting to install the `latest` version of `corepack`:
```
#21 178.0 + npm install -g corepack@latest
#21 182.5 npm WARN EBADENGINE Unsupported engine {
#21 182.5 npm WARN EBADENGINE   package: 'corepack@0.21.0',
#21 182.5 npm WARN EBADENGINE   required: { node: '>=18.17.1' },
#21 182.6 npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '9.2.0' }
#21 182.6 npm WARN EBADENGINE }
```
This started when the `latest` version of `corepack` was updated to specify a higher `engine` range in it's `package.json`. The resulting image _appeared_ to still function, but it is unclear if that is just a coincidence. This change makes it obvious when there is an unsupported engine by changing the warning to an error, with the …
=> feat: enforce strict engine control for `npm`

Dockerfile, Dockerfile.slim
This was initially addressed in #329, but it has since been found that some more tools get used based on a home directory. These additional findings are due to testing lockfile generation more fully and not simply relying on the successful installation and access of each required tool from a non-root user/group that does not map to a user/group account already in the container.
The following additional tools are susceptible to the same issue and therefore have been provided with explicit install/home directories that allow them to be globally accessible:
* Phylum, `pip`, and any other tool that supports the XDG spec
* Dotnet
* Go
* Git
The XDG and `git` changes were also applied to the slim image creation since Phylum, `pip`, and `git` are available there.
Changes from this PR have been …
=> fix: more container tools broken when home-less

.pre-commit-config.yaml, pyproject.toml, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py
https://github.com/astral-sh/ruff/releases/tag/v0.1.1
=> chore: update for the ruff v0.1.1 release

CONTRIBUTING.md, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/cli.py, src/phylum/ci/common.py, src/phylum/ci/depfile.py, src/phylum/ci/lockfile.py, src/phylum/exts/ci/main.ts, tests/unit/test_lockfile_parse.py
This change speeds up overall execution time, especially for manifests.
It does this by caching the results of parsing dependency files from the
current (HEAD) location under analysis. This reduces the instances of
parsing the same file from three to two. Previously, it would happen:
* When filtering files supplied as input
* When calculating the new dependencies
* File has changed (or `--force-analysis` provided) and `--all-deps`
not supplied
* This one is eliminated via caching
* When submitting the files for Phylum analysis
* During the `PhylumApi.parseLockfile` extension API call
* This one remains since the extension API does not recognize the
Python cache
There is also large change to rename internal uses of `lockfile` term.
This was done in a separate commit and includes the …
=> feat: cache parsing results of current dependency files

src/phylum/ci/ci_none.py
This change uses the `git_set_remote_head` helper function in the `CINone` implementation to ensure the remote `HEAD` ref is set for the cases where it is used. This happens in the `common_ancestor_commit` and `is_any_depfile_changed` properties. In each case, the function is used as a fall back instead of pre-emptively to minimize calling commands that require git credentials.
This change initially came from a request from @louislang, who noticed a hard failure when running `phylum-ci` locally, for an integration that does not have it's own customized implementation. It also occurred for @cd-work, while using `phylum-ci` in a Circle CI orb.
Here is what it looks like in action:
<details><summary>Details (click to expand)</summary>
<p>
```
../phylum-ci  10  17 on  more_head_checks [!] …
```
=> feat: ensure remote `HEAD` set for `CINone` implementation

src/phylum/ci/ci_azure.py, src/phylum/ci/ci_github.py
The repository URL is sometimes incorrectly formatted with `False` values instead of the correct environment variable. This happens because the walrus operator assignment is not properly delimited. For instance, the GitHub CI environment would incorrectly report the repo URL:
```
WARNING  Repository URL differs from what would be set! Keeping existing value.
Existing: https://github.com/maxrake/delme
Proposed: False/False
Use CLI to override: https://docs.phylum.io/docs/phylum_project_update
```
This change ensures the walrus operator assignment is parsed as intended.
=> fix: repository URL sometimes formatted with `False`

src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/depfile.py, src/phylum/ci/git.py
This change seeks to clean up a few things that were discovered during recent testing, and to do so before the next release. The use of walrus operators (i.e., `:=`) has been removed in favor of more, but simpler, code. Multiline log messages have been trimmed a bit after it was discovered that lines with >71 characters wrap in constrained environments where the WIDTH is fixed at 80 characters (e.g., GitHub Actions). This is due to the space between the log level (e.g., `WARNING`) and the message being two characters instead of the assumed one, allowing a max of 71 characters for each line of the message instead of 72 as previously assumed. There is likely a better way to programmatically account for this with something in the `textwrap` module, but these small changes will do for now.
=> refactor: trim log messages and remove walrus operators

.pre-commit-config.yaml, Dockerfile.slim, README.md, scripts/docker_tests.sh, src/phylum/ci/ci_base.py, src/phylum/ci/ci_github.py, src/phylum/ci/depfile.py
NOTE: This PR is not meant to be merged until after the docs.phylum.io page is cutover from being hosted on README.com to GitHub Pages.
=> docs: update documentation links

Dockerfile.slim
This change uses `strip` to reduce the `phylum` binary size. This idea comes from a blog post about making Rust release binaries smaller:
https://kobzol.github.io/rust/cargo/2024/01/23/making-rust-binaries-smaller-by-default.html
Instead of making the change in the release workflow of the Phylum CLI, the binary stripping is limited to the `slim` Docker images here in an effort to reduce the size for performance-oriented applications. The benefit is a smaller image and therefore faster download times.
Benchmarks from this change on my local system:
* Image generation duration increased by a few seconds
* This is due to installing and then removing the `binutils` package
* The `phylum` binary size went from 124MB --> 90MB
* Uncompressed image size went from 380MB --> 344MB
* Compressed …
=> perf: reduce `phylum` binary size for slim images

Dockerfile
The lockfile generation tool `yarn` fails when used in the `phylum-ci` Docker image as a non-root user. An example of the failure can be seen from the output of the "smoke test," which is using `scripts/docker_tests.sh` to ensure basic functionality:
```
yarn --version
Internal Error: EACCES: permission denied, open '/usr/local/corepack/lastKnownGood.json'
Error: EACCES: permission denied, open '/usr/local/corepack/lastKnownGood.json'
```
The same behavior happens for `pnpm`. These are the tools installed by `corepack`, which changed recently to "Bump Known Good Release when downloading new version" (https://github.com/nodejs/corepack/pull/364). Part of that change was to make use of the `COREPACK_DEFAULT_TO_LATEST` environment variable to *not* update the last known good version, but …
=> fix: image failures for non-root uses of `yarn` and `pnpm`

.github/workflows/auto_updates.yml, CONTRIBUTING.md, poetry.lock, src/phylum/ci/ci_base.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/git.py, tests/functional/test_ci.py, tests/functional/test_init.py
Testing was performed locally and bug free functionality confirmed by updating `poetry.lock` with the latest dependencies and ensuring it passed the `pre-commit` hooks while submitting this change. Some small formatting changes were applied here. Guidance and implementation was updated to specify `--no-cache` when updating dependencies with Poetry. That way, the results will be the same regardless of where it happens (e.g., locally vs. CI).
Closes #394
=> fix: `pre-commit` hook failures

docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/git_precommit.md, docs/integrations/github_actions.md, docs/integrations/gitlab_ci.md
This change restores the integration documentation that was previously stored in this repository by copying it from the `documentation` repo (no additional changes were made). That way, the code and docs will live together and be maintained more easily.
This is the first step in a three-step process. The second step is to update the `documentation` repo to include these integration docs as a git submodule, in the same way as is done for the `cli` repo. The third step is to ensure releases of `phylum-ci` trigger a sub-module update in the `documentation` repository.
This change is also acceptable because the `phylum-ci` repo is also public and therefore available to view and suggest/submit changes directly from the docs.phylum.io website.
=> docs: restore integration documentation

.pre-commit-config.yaml, README.md, docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/git_precommit.md, docs/integrations/gitlab_ci.md, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/cli.py, src/phylum/ci/depfile.py, src/phylum/ci/git.py, src/phylum/github.py, src/phylum/init/sig.py, tests/functional/test_init.py, tests/unit/test_sig.py
This change introduces audit mode in the form of an `--audit` flag. It also adds a `--skip-comments`/`-s` flag to disable posting comments/notes on pull/merge requests. This flag is implicitly set when audit mode is enabled. The documentation was updated to match. Additionally, a change was made to use `inspect.cleandoc` instead of `textwrap.dedent` everywhere. Using `cleandoc` is preferred since it allows for removing the ugly line continuation character from multiline strings.
Closes #396
Closes #311
A Docker image was created with the changes in this PR and hosted [under my account](https://hub.docker.com/repository/docker/maxrake/phylum-ci/tags) as the `audit_mode` tag. It was used to test the CI environments. Results were good.
=> feat: implement audit mode

src/phylum/ci/ci_bitbucket.py, src/phylum/init/cli.py
This change was made after discovering that Atlassian Compass components
recognize Bitbucket repository URLs only when they are `HTTPS:` and not
when they are `HTTP:`, even though that is how the URL is provided when
obtained by getting the `BITBUCKET_GIT_HTTP_ORIGIN` environment variable
value.
Additionally, the `is_token_set` function was refactored to adhere to
the new `ruff` preview rule `SIM103`. The latest release of `ruff`
introduced the new linting rule [SIM103: needless-bool](https://docs.astral.sh/ruff/rules/needless-bool),
which causes the code in question to fail when run in preview mode. This
change was made now to get ahead of the rule, for when it enforces the
implicit `else` cases by default. The change was made in a way that
seeks to maintain readability and intent. Type …
=> feat: ensure Bitbucket repo URLs use HTTPS scheme

docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/gitlab_ci.md
This change updates the docs for the integrations that allow for triggering Phylum analysis upon pushes to the default branch: GitLab CI, Azure Pipelines, and Bitbucket Pipelines (GitHub Actions currently only runs in the context of `pull_request` webhook events).
The change is made to coincide with the upcoming platform feature enabling default labels. It is meant to ensure the Phylum analysis results for the branch associated with that label are current.
=> docs: recommend triggering scans for default branch

src/phylum/init/cli.py
This fix accounts for the possibility of the Phylum CLI version reporting with a trailing `+` character. This is the `cargo_suffix` and indicates when the version was obtained by Cargo instead of git, which happens for homebrew installed instances of the Phylum CLI.
The fix here simply removes any trailing `+` character when obtaining the version from a `phylum --version` command. This approach allows the rest of the version checking/handling code to remain intact.
References:
* [Phylum CLI code](https://github.com/phylum-dev/cli/blob/a9c29420322f866880d11df48c9c324fbe7911b9/cli/src/app.rs#L8)
* [`git_version` crate docs](https://docs.rs/git-version/0.3.9/git_version/macro.git_version.html)
* [`CARGO_PKG_VERSION` envvar docs](https://doc.rust-lang.org/cargo/reference/environment-variables. …
=> fix: account for `cargo_suffix` in CLI version

docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/git_precommit.md, docs/integrations/github_actions.md, docs/integrations/gitlab_ci.md
This change seeks to improve the integration documentation by acting on user feedback. In particular, the following suggestions were taken:
* Add detail on how to use audit mode with the `pre-commit` hook
* Make debug/verbose output the default in recommended CI configurations
* Be more explicit about the GitHub Action options
* The default action uses the `latest` tag from the `phylum-ci` Docker image and should be used unless there is a good reason not to
* The alternative options have callouts and notes now making it more clear that their configurations should only be used if the default action does not suffice
A separate PR will be made in the `phylum-analyze-pr-action` repo, to include the same changes here.
=> docs: update docs based on user feedback

.github/workflows/release.yml
This change fixes a small logic error in the release process. The value used to compare whether a release needs to be forced as a patch release (due to no bump-worthy changes found by Python Semantic Release) was overwritten before it was saved off. That is no longer the case. The environment variable name was also changed to make the difference between what Python Semantic Release thinks the next release version should be and what the actual next release version will be more obvious.
=> ci: ensure forced patch releases are possible

.github/workflows/phylum_analyze_pr.yml
The `phylum-analyze-pr-action` was recently updated to make debug output the default. A new tag and release was created for that action to include the change. This PR updates the action to that version and removes the custom `cmd` entry since it is no longer different than the default.
=> ci: update to latest Phylum GitHub action

Dockerfile, Dockerfile.slim, docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/git_precommit.md, docs/integrations/github_actions.md, docs/integrations/gitlab_ci.md, docs/integrations/jenkins.md, scripts/docker_tests.sh, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_jenkins.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/cli.py
This change adds an integration for the Jenkins pipelines CI
environment. Specifically, it adds support for declarative pipeline
syntax in multibranch pipelines. Pipeline runs for both PRs and branches
are supported.
This integration detects and handles both branch pipelines and pull
request (PR) pipelines. When in the PR pipeline context, the results
are only written to logs and NOT as a comment on the PR. This is due to
the nature of the environment, where many different source repositories
are supported (e.g., GitHub, Bitbucket, GitLab, etc.)
The `documentation` repo will be updated separately to add this
integration to the summary overview page.
Several formatting changes were made throughout the code base, in a
separate commit, to include:
* Be consistent on the spelling of …
=> feat: add support for Jenkins Pipelines

Dockerfile, Dockerfile.slim, scripts/docker_tests.sh
This change is based on a request from users of `podman`. Older versions of that tool (prior to v4.6.0) require `ps` to exist on the running container in order to use the `top` command while newer versions do not.
This package adds about 340kB to the compressed image size.
An image was built with these changes and provided for testing as the `phylumio/phylum-ci:with_ps` tag on
[Docker Hub](https://hub.docker.com/r/phylumio/phylum-ci/tags). The user in question has confirmed that the change works for them.
=> feat: add `ps` to Docker images

.phylum_project, docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/git_precommit.md, docs/integrations/gitlab_ci.md, docs/integrations/jenkins.md, src/phylum/ci/ci_base.py, src/phylum/ci/cli.py, src/phylum/ci/common.py
This change allows users to specify a group without also specifying a corresponding project. Neither the project nor the group needs to exist beforehand. The group will now be created if it does not already exist.
This behavior is useful for those users with many projects and a desire to provide analysis results in the context of organizational groups. They can now specify a single CI configuration to use across the enterprise and everything will be named and created automatically and consistently.
Additionally, the values for project and group are now allowed to be "mixed" between what is specified on the command line and anything found in a `.phylum_project` file. This "mixing" was specifically denied previously but allowed now with a warning to let users know that may be an unexpected …
=> feat: allow groups to be specified without a project

README.md, pyproject.toml
This is a cleanup, to add a missing link to the Jenkins documentation in the README. It also shortens the project tagline a bit (based solely on updated personal preferences). Lastly, some image tag references are updated to more recent versions.
=> docs: add missing Jenkins link

Dockerfile, Dockerfile.slim
This change adds support for [git large files storage](https://git-lfs.com/) (lfs) by adding the `git-lfs` package to both the default and `slim` Docker images. This change was prompted by a user request and barely increases the uncompressed image size. The feature will be useful for anyone making use of git lfs in the repositories they wish to analyze with Phylum.
=> feat: add `git-lfs` to Docker images

poetry.lock, pyproject.toml
This change pins the `python-semantic-release` (PSR) dependency to the last known working version of v9.8.3. After that release, a number of large refactors were made and introduced breaking changes, even though they were only bugfix releases (I know, the irony). Specifically, the `context` variable stopped being defined for the release notes template.
This variable is used in the `phylum-ci` project to create "compare" links for making it easy to see what has changed from the previous release. Instead of removing the compare link from the template, the PSR dependency was pinned, with a note to remove the pin [when PSR fixes the regression](https://github.com/python-semantic-release/python-semantic-release/issues/984).
=> build: pin `python-semantic-release` to v9.8.3

poetry.lock, pyproject.toml, templates/.release_notes.md.j2
This change is an update to the one made in #454. Since then, the `python-semantic-release` (PSR) dependency has responded to their breaking change by re-defining the `context` variable for release notes templates. However, they also say that the variable was not meant to be exposed in the first place and that it will be removed again in the next major version release. Therefore, the pin has been changed to a caret-style one to allow for getting future releases that are at least v9.8.7 but less than v10.
Discussions with the maintainer are ongoing, to request the features relied upon with the current implementation are accounted for in the next major version release.
References:
* https://github.com/python-semantic-release/python-semantic-release/pull/1005
* …
=> build: update `python-semantic-release` pin

docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/git_precommit.md, docs/integrations/gitlab_ci.md, docs/integrations/jenkins.md, poetry.lock, pyproject.toml, src/phylum/ci/ci_base.py, src/phylum/ci/cli.py
This PR adds a new feature to specify exclusions to the dependency
files found/detected when not explicitly specified by argument. The
new option accepts gitignore-style patterns, using the [`pathspec`
third-party library](https://python-path-specification.readthedocs.io/en/stable/readme.html).
Closes phylum-dev/roadmap#462
The changes in this PR are available for testing with the `maxrake/phylum-ci:exclusions` Docker image found [on Docker Hub](https://hub.docker.com/r/maxrake/phylum-ci/tags).
The changes were tested explicitly for each of the following environments:
* Locally
* pre-commit
* GitHub Actions
* Jenkins
The changes were not tested in the following environments since the syntax for pipeline specification is the same (YAML) as for GitHub Actions:
* Azure
* Bitbucket
* GitLab …
=> feat: add option to exclude dependency files

README.md, docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/git_precommit.md, docs/integrations/github_actions.md, docs/integrations/gitlab_ci.md, docs/integrations/jenkins.md, src/phylum/ci/cli.py, src/phylum/ci/common.py
This change documents the various exit codes in use for the `phylum-ci` script entry point. The documentation for integrations that make use of this script were updated to include a reference to the detail. The debug output now includes a link to that same detail.
This change was generated from a user request. They were curious to know why a failing status check was reported when a successful analysis comment was added to their PR. They didn't understand what exit code 10 meant. This specific situation is already answered in a FAQ and now is more likely to be seen since it is referenced in the exit code table.
=> docs: add exit code information

.github/workflows/release.yml
This change corrects a bug in the release workflow where the `phylum-ci.exe` artifact is not published to the newly created GitHub release. The `python-semantic-release` tool has the following config, in `pyproject.toml`, for publishing artifacts by pattern:
```
[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*", "build/phylum-ci.exe"]
```
The issue was that the `actions/upload-artifact` step used `phylum-ci.exe` as the artifact name, which resulted in the following directory structure for the corresponding `actions/download-artifact` step:
`./phylum-ci.exe/phylum-ci.exe`
This clearly won't match the glob pattern of `build/phylum-ci.exe`. So, this change is a simple one: change the upload artifact name to `build` so that the downloaded artifact will exist at …
=> fix: include `phylum-ci.exe` in release artifacts

.github/workflows/preview.yml, .github/workflows/release.yml, README.md, pyproject.toml
This change adds another Windows standalone "installation" option, in the form of a zip archive that contains all the files needed to run the `phylum-ci.exe` binary...which is also included in the archive. This option is not as convenient as the single file self-extracting executable since it requires an additional unzipping step. It does have the advantage of not getting flagged by antivirus. This option was added based on direct feedback from an existing customer and directed by @furi0us333.
The changes from this branch were tested in a Preview workflow run made from a `standalone_test` branch and can [be viewed here](https://github.com/phylum-dev/phylum-ci/actions/runs/11258132652). The zip archive did not flag AV and the contents were successfully used on a Windows system to analyze a …
=> feat: add Windows standalone archive install option

.github/workflows/release.yml
This change accounts for the time it takes to publish a release on PyPI (or TestPyPI) and when that release is available for use. The test steps in CI would sometimes fail because they expected the release to be available immediately after publication. Now, the step will try for up to three minutes before failing the step, which appears to be plenty of time based on previous observations.
=> ci: add waits for PyPI publications

docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/git_precommit.md, docs/integrations/gitlab_ci.md, docs/integrations/jenkins.md, src/phylum/ci/ci_base.py, src/phylum/ci/cli.py, src/phylum/constants.py, src/phylum/exts/ci/main.ts, src/phylum/init/cli.py
This change adds support for organizations. It does so by adding an optional `--org` argument to the `phylum-ci` entry point. That argument will take precedence over any value found in the Phylum settings file. The argument and all the logic and documentation around it allow for no org to be specified. This is intentional since there will have to be a transition period where some users may not be using orgs just yet.
When an org is specified, it is required that a group also be specified. However, it is still possible to specify a group without an org and even no group at all. The log output was updated to make it more clear which project/org/group combo is in use.
Additional changes made include:
* Update the custom `ci` Phylum analysis extension
* Add `--org` option and use it when …
=> feat!: add organization support

CHANGELOG.md, pyproject.toml, templates/.release_notes.md.j2
This update changes `ctx` to `context` in the release notes environment for Python Semantic Release (PSR). The pinned version of PSR, v9.12.0, has a bug where `ctx` is not a valid shorthand for release notes templates. This bug was fixed in PSR v9.12.1, but updating to a newer version of PSR always carries a risk of breaking changes. Such an update will be attempted at a later time.
I also had to back out the changes made by the bad v0.52.0 version bump
made by PSR. The tag has already been deleted.
=> ci: `ctx` not available in release notes PSR env

README.md, src/phylum/ci/ci_base.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/common.py, src/phylum/logger.py
This change accounts for the possibility that there are no current dependencies to analyze, even with recognized dependency files. Before this change, the `phylum-ci` entry point would exit with an unhandled exception and a large stack trace due to an empty analysis result being returned from the custom `ci` extension. Now, the situation is recognized and handled cleanly with a descriptive warning and new system exit code of `12`.
Other changes made include:
* Remove old dead code checking for CLI exit code value of `100`
* The analysis is performed with the custom `ci` extension now
* Use `SystemExit` in `CIPreCommit` instead of `sys.exit`
* Exit with the current return code
* Format and refactor throughout
* Add link to phylum project file docs in error message
* Add initial debug log …
=> fix: exit cleanly when no current dependencies

src/phylum/ci/ci_base.py, src/phylum/ci/depfile.py, src/phylum/ci/git.py
This change accounts for the possibility that dependency files are specified or detected at levels lower than the root git directory. This is the case when analysis is started in a sub-directory (e.g., monorepos).
When determining the base dependencies to make sure only the newly added dependencies are considered, a temporary git worktree is created with the common ancestor commit. That worktree is of the **entire** git repo at that commit and therefore the relative path to dependency files specified/detected at lower levels in the path are not correct. The effect is an error in parsing the file due to it not existing (at the expected path).
The fallback when this happens is to assume that all current dependencies are new and to analyze them (e.g., the same as if the `--all-deps` option …
=> fix: account for analysis started in repo sub-dirs

.pre-commit-config.yaml, pyproject.toml, src/phylum/ci/ci_base.py, src/phylum/constants.py, src/phylum/init/cli.py
This change updates the version processing logic to avoid GitHub API calls when a Phylum CLI is already installed and its version is supported. This is especially useful for the Docker image, where there is already a known good Phylum CLI bundled in. This change originated with a user request where they are seeking to limit outbound network requests.
There is also an effort made to be more intentional about the difference between Phylum CLI versions *to be* installed vs. those that are already installed.
Other changes made include:
* Create a new `is_installed_version_supported` predicate
* Use it instead of scattered checks against `MIN_CLI_VER_INSTALLED`
* Update `ruff` to latest version
* Format and refactor throughout
* Rename `is_supported_version` to …
=> feat: avoid GitHub API calls during version check

Dockerfile
Lockfile generation for `gradle` manifests started failing recently with the following error message:
```
Toolchain installation '/usr/lib/jvm/java-17-openjdk-amd64' does not
provide the required capabilities: [JAVA_COMPILER]
```
This is due to
[a known regression](https://github.com/gradle/gradle/issues/30264) introduced in Gradle v8.10. This regression is also documented in the [upgrading guide](https://docs.gradle.org/current/userguide/upgrading_version_8.html#javacompile_tasks_may_fail_when_using_a_jre_even_if_compilation_is_not_necessary), with a suggested fix. However, that fix would require updates in Phylum user repositories...which is not always possible or desired. Instead, this change updates the Docker image to include the java compiler in the form of the system package …
=> fix: `gradle` lockfile generation requires `javac`

README.md, docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/git_precommit.md, docs/integrations/github_actions.md, docs/integrations/gitlab_ci.md, docs/integrations/jenkins.md, scripts/docker_tests.sh, src/phylum/ci/ci_base.py, src/phylum/ci/cli.py, src/phylum/ci/common.py
This change adds an `--ignore-errors` flag to allow for explicitly ignoring non-analysis warnings and errors that would otherwise affect the exit code. All modifications to the `phylum-ci` return code are now handled in one spot, the class property setter method. This ensures all the logic for setting known return codes (i.e., `2` or greater) is grouped together.
Making this change helped to identify (and fix) a bug where dependency file filter failures (exit code `10`) were incorrectly suppressed when the analysis was incomplete but without any analysis failures.
Additional changes made include:
* Add script entry point debug log entry to show args it was called with
* Add Docker image test to ensure `javac` is installed and on the PATH
* This should have been included in #507
* Update …
=> feat: Allow for ignoring non-analysis errors

src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_jenkins.py, src/phylum/ci/ci_none.py, src/phylum/ci/common.py, src/phylum/init/cli.py
The `ruff` linter has a "preview" mode to show lint findings that are still experimental or otherwise not included in the default set of checks. This change set addresses the following findings in an effort to get ahead of these coming out of preview:
* RUF052: used-dummy-variable
* Rename `_path` initVar in `DepfileEntry` dataclass to `path_`
* PLR0904: too-many-public-methods (22 > 20)
* Change two `CIBase` class public methods to private
* `update_depfiles_change_status` -> `_update_depfiles_change_status`
* `git_root_dir` -> `_git_root_dir`
* PLR0914: too-many-locals (16 > 15)
* Extract logic to install the Phylum CLI in `phylum-init` -> `main`
NOTE: the other current preview findings are either false positive (LOG015) or related to docstring changes...which will be either ignored or …
=> refactor: address `ruff` preview lint findings

README.md, docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/git_precommit.md, docs/integrations/github_actions.md, docs/integrations/gitlab_ci.md, docs/integrations/jenkins.md, src/phylum/ci/ci_base.py, src/phylum/ci/cli.py
This change adds a flag named `--fail-incomplete` to set a failure code when some analysis results are unknown. This is useful in environments where strictness is desired to prevent adding any new dependency until it passes established policy. This is a mutually exclusive option with `--audit`.
The name `--strict` was also considered but not used because that name implies a "strict mode" which would be more than just the opposite of audit mode. For instance, the ability to ignore errors with the `--ignore-errors` flag should not be possible in a true strict mode. So, the more specific option name was used to limit the effects of specifying it.
The changes in this PR are available for testing with the `maxrake/phylum-ci:stricter` Docker image found [on Docker …
=> feat: add option to fail for incomplete analysis

src/phylum/ci/ci_base.py, src/phylum/ci/cli.py
This change forces analysis when a new project is created. This ensures the project is initially populated with results in the Phylum UI, which helps for users configuring Phylum analysis exclusively through the CI integrations. This is doubly true when the set of dependency files do not include a manifest, which is the other trigger for automatically forcing analysis.
The desire expressed from users of the integrations is that setting up the integration and running it the first time should cause the project dependencies to be ingested without needing to set the `--force-analysis` flag or wait until a PR with a modified dependency file emerges. They also don't want to have to use the Phylum CLI to populate the project(s) before scanning them with the CI integrations.
This is what it looks …
=> feat: automatically analyze newly created projects

.github/workflows/phylum_analyze_pr.yml
This change takes advantage of the new `--fail-incomplete` flag to be more strict in how the Phylum analysis check is handled. Before this change it was possible to merge a PR with new/changed dependencies even before the Phylum analysis was complete. With this change, the status check will report as a failure, blocking the ability to merge, when the analysis is incomplete. This provides a degree of strictness to prevent adding *any* new dependency until it passes established policy.
=> ci: prevent PR merges when analysis is incomplete

.github/workflows/auto_updates.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/test.yml, CONTRIBUTING.md, Dockerfile, Dockerfile.slim, README.md, poetry.lock, pyproject.toml, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_base.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py, src/phylum/ci/ci_jenkins.py, src/phylum/ci/ci_none.py, src/phylum/ci/ci_precommit.py, src/phylum/ci/cli.py, src/phylum/ci/common.py, src/phylum/ci/depfile.py, src/phylum/ci/git.py, src/phylum/console.py, src/phylum/github.py, src/phylum/init/cli.py, src/phylum/logger.py, tests/unit/test_package_metadata.py, tox.ini
This change accounts for the release of Python 3.13, which happened
07 OCT 2024. Anyone tracking this repository and this change should
update their use of `pyenv` locally, to include py3.13.x.
Changes made to add Python 3.13 support include:
* Update the Docker base image version
* Update the CONTRIBUTING documentation
* Update the testing environments in `tox`, workflows, and unit tests
* Update `pyproject.toml` and generate an updated `poetry.lock` lockfile
* The existing `poetry-core` specified minimum requirement still works
Changes made to remove Python 3.9 support include:
* Update `pyproject.toml` and regenerate `poetry.lock`
* Upgrade target version for QA tools
* Use the `--fix` option of `ruff` to automatically update code
* Use the pipe (`|`) operator for type annotations …
=> feat!: add Python 3.13 support and drop Python 3.9 support

README.md, docs/integrations/azure_pipelines.md, docs/integrations/bitbucket_pipelines.md, docs/integrations/gitlab_ci.md, src/phylum/ci/ci_azure.py, src/phylum/ci/ci_bitbucket.py, src/phylum/ci/ci_github.py, src/phylum/ci/ci_gitlab.py
This change removes the `SUCCESS` comments from pull requests (PRs) and merge requests (MRs). Other comment types are unchanged. This change is necessary because the `SUCCESS` comments are considered by existing customers to be too noisy and not useful since the related status check will show as passing when the analyis is successful. Plus, the logs contain the same information as was included in the `SUCCESS` comments.
Closes #78
BREAKING CHANGE: PRs/MRs will no longer have `SUCCESS` comments.
The changes in this PR are available for testing with the `maxrake/phylum-ci:quiet_wins` Docker image found [on Docker Hub](https://hub.docker.com/r/maxrake/phylum-ci/tags).
---
This is what it looks like when a PR is created on GitHub with a lockfile that includes changes where the analysis is …
=> feat!: remove `SUCCESS` comments from PRs/MRs

poetry.lock, pyproject.toml
This change restricts the `rich-codex` dependency from using a version that does not work to validate configs. A regression was added to the tool in the v1.2.9 release and has been fixed with a PR that has been merged but not yet included in a release. This is a "restriction" instead of a pin because the two versions that are restricted are known to be non-functional while previous and future versions are functional.
=> ci: restrict `rich-codex` dependency range

.github/dependabot.yml
The configuration introduced in #568 was wrong and this PR fixes it.
It was not possible to test Dependabot in that branch because it only
works when the configuration is on the default branch. The error
provided was:
```
Dependabot encountered the following error when parsing your .github/dependabot.yml:
The property '#/updates/0/registries' of type string did not match one or more of the required schemas
Please update the config file to conform with Dependabot's specification.
```
The documentation is short on details, especially regarding the schema,
but it turns out the referenced `registries` in the `updates` key are
meant to be provided as a list instead of a string. This can be seen
in the [example provided for Maven](https://docs.github.com/en/code-security/dependabot/working-with- …
=> build: fix Dependabot config

.github/workflows/preview.yml, .github/workflows/release.yml
This change accounts for a breaking major version update in the GitHub action `actions/download-artifact`, released three weeks ago.
The breaking change was inspected at the time and not deemed to affect this repository. However, that does not appear to be the case since the preview workflow is failing now in a way that makes it appear the download was placed in the working directory instead of a new subdirectory with the same name as the artifact. The working assumption is that the action, when used with all default values, is behaving as if artifact IDs were provided, which triggers the changed behavior in the new version of the action.
This PR ensures that each use of the `download-artifact` action specifies explicit `name` and `path` inputs for the artifact.
Ref: …
=> ci: specify artifact download name and path

.github/workflows/preview.yml, .github/workflows/release.yml, CHANGELOG.md, pyproject.toml
This change reverts the previous release bump commit since the release workflow failed. The reason it failed is due to the `pyproject.toml` config file not getting updated correctly with the new version. This has been corrected, by configuring Python Semantic Release (PSR) to update the version in the new location. This change was tested locally and should be the last one needed to fix this repo's release workflow 🤞
The previous GitHub tag and release were also reverted/removed so that the next time a release workflow is started it will use the v0.59.0 version, as expected.
=> build: fix the release
