phylum-dev/phylum-ci

.github/pull_request_template.md
.github/workflows/test.yml
README.md
src/phylum_ci/__init__.py

This is the first step in closing #2 since a workflow has to exist on the default branch _before_ it can be used manually to iterate on. This workflow may not work...and that is the point. It won't be possible to ensure it works until it is already in place. There will be follow on PR(s) to properly address and close #2
This partially addresses issue #2

Get first draft of first workflow in place

---

.github/workflows/preview.yml
.github/workflows/release.yml
.github/workflows/test.yml
README.md
poetry.lock
pyproject.toml
tests/test_phylum_ci.py

* Complete the test workflow
* Switch to a test-matrix style job with a roll-up job to aggregate the results
* This was also done in the CLI test workflow
* It helps for only having to specify a single, statically named job as a required status check in the repo protected branch settings
* Add stubs for the preview and release workflows
* They will be completed in #13
* Add more tests for the package/project metadata
closes #2

Add initial workflows

---

src/phylum/ci/ci_base.py

This change enables links for when analysis is performed when in a group and when no group is defined. It also takes into account the label used during the analysis so that the exact page for the analysis is returned instead of just the default one.
Closes #42
- The change here will apply to the (not yet created) GitHub integration in this repo
- It will not affect the [phylum-analyze-pr-action](https://github.com/phylum-dev/phylum-analyze-pr-action) repo, which still has this issue
- CC: @furi0us333 for guidance about fixing in the other repo or simply waiting out the time until there is a GitHub integration in `phylum-ci` (currently 4th [in the backlog](https://github.com/orgs/phylum-dev/projects/23/views/1))
- Still no automated tests, but local tests and tests in a private GitLab repo …

fix: enable Phylum UI links for groups

---

CONTRIBUTING.md
src/phylum/ci/ci_gitlab.py
src/phylum/ci/ci_none.py
src/phylum/ci/ci_precommit.py
src/phylum/ci/cli.py

This PR adds an option to force analysis of the lockfile, even when it hasn't changed.
This PR also includes a fix to ensure the "CI Platform Name" portion of a label is correct. The order was wrong and all the labels were getting the default value of "Unknown". That fix can also be seen in the output below.
The PR will not be squashed...so that the proper tracking of the feat and fix will remain.
Closes #45
- Still no automated tests; confirmed locally...see output below
```
❯ poetry run phylum-ci -l poetry.lock --all-deps
[+] No CI environment detected
[+] Confirming pre-requisites ...
[+] Existing `.phylum_project` file found at: /Users/coggins/dev/phylum/phylum-ci/.phylum_project
[+] `git` binary found on the PATH
[+] Existing `.git` directory was found at the current working …
```

feat: provide an option to force analysis

---

.phylum_project

- Updating `.phylum_project` file to leverage group accounts

ci: update `.phylum_project` file

---

Dockerfile
README.md
docs/github_actions.md
entrypoint.sh
src/phylum/ci/ci_github.py
src/phylum/ci/ci_gitlab.py
src/phylum/ci/cli.py

* Add support for GitHub Actions CI environment
* The existing behavior in `phylum-analyze-pr-action` is maintained
* Comments are added to the PR with the `issues` API instead of the `pulls` API
* See [Working with comments](https://docs.github.com/en/rest/guides/working-with-comments) for why
* Looking for existing phylum comments to avoid duplicated comments only takes into account the first 100 comments
* The API does not provide a way to get the comments in descending order
* There is a pagination traversal method available...but using that may have to go in another issue
* Allow the running image to be called with an entrypoint
* An `entrypoint.sh` script was added to the image, available to be called by the container with the `--entrypoint` option
* An `ENTRYPOINT` entry was NOT …

feat: add support for GitHub Actions CI environment

---

README.md
docs/sync/azure_pipelines.md
docs/sync/git_precommit.md
docs/sync/gitlab_ci.md
docs/sync/integrations_overview.md
src/phylum/ci/ci_azure.py
src/phylum/ci/ci_base.py
src/phylum/ci/ci_none.py
src/phylum/ci/cli.py

This new integration:
* Supports Azure DevOps Services, for code hosted in Azure Repos
* It only supports git repositories
* It only supports Pull Request triggers
* It adds comments to the PR (like the GitHub & GitLab integrations)
* Meant to be used as a container job
* Exposed with existing native pipeline tasks
* No new tasks or extensions are needed/created
* The pipeline takes ~20-30 seconds to run
* Most of this time (~10-15s) is spent initializing the container
* Azure Pipelines handles container jobs differently, which accounts for this added time
* The output is posted as a comment on the PR in the same way as was done for GitHub and GitLab
* Alternative output methods were discussed with @furi0us333 and the decision was made to limit differences from other integrations until a …

feat: add support for Azure Pipelines CI environment

---

docs/sync/azure_pipelines.md
docs/sync/git_precommit.md
docs/sync/gitlab_ci.md

docs: use long form options in documentation examples

---

docs/sync/azure_pipelines.md
src/phylum/ci/ci_azure.py
src/phylum/ci/ci_base.py
src/phylum/ci/ci_github.py
src/phylum/ci/ci_gitlab.py
src/phylum/ci/ci_none.py
src/phylum/ci/ci_precommit.py
src/phylum/ci/cli.py
tests/unit/test_package_metadata.py

Adding support for additional repository types supported by Azure Pipelines is basically a task in tracking the build repository provider and then altering the logic and environment variables used based on that provider. This known as the "triggering repo" and this change makes it so both "Azure Repos Git" and "GitHub" repos are supported.
The actions made in this changeset include:
* Track the build repository provider that triggered Azure Pipelines CI
* `TfsGit` is really "Azure Repos Git"
* Add GitHub as a supported triggering repo
* Update documentation
* Update the `post_output` method in the `CIBase` class
* Don't require it to be an unimplemented abstract method
* Implement default behavior in the base class to post the output of the analysis as markdown rendered for output to the …

feat: extend Azure Pipelines integration to support GitHub repos

---

README.md

See: https://github.com/badges/shields/issues/8671

chore: fix README test status badge

---

src/phylum/ci/ci_base.py

This change addresses a formatting anomaly in the terminal/log output where the link to the way project in the Phylum UI was getting clipped and then no longer functional as a clickable link in the environments where links are rendered as clickable.
The `connect-markdown-renderer` and `rich` libraries are responsible for rendering the markdown in a terminal. The width is automatically determined and for some CI environments the width is smaller than the link, causing it to get clipped.
The library method in use now does not allow for specifying different behavior. If it did, the easiest solution would be to pass `soft_wrap=True` through to the instantiation of the `Console` class in `rich`.
Instead, the link display was removed from the markdown for the output that gets posted to logs and …

fix: link to Phylum UI project clipped in logs

---

CONTRIBUTING.md
docs/sync/integrations_overview.md

I will make the changes manually to expedite them until this is pushed via automation.

docs: align to main website

---

src/phylum/ci/ci_base.py
src/phylum/ci/common.py

This change ensures that comments are constructed in a deterministic and consistent manner. Any packages with risk findings will be sorted, first by the package name and version. Then, the individual issues for a given package are sorted by severity level (critical --> info), risk domain, and title. The result of these changes should ensure that PR comments are not posted again when the only difference from the previous `phylum-ci` generated comment is the order of the content within the comment.
Fixes #193
Contents of a Python dependency file, `reqs.txt`, that contains known bad packages:
```
../phylum-ci  7  18 on  prevent_dup_comments [?] is 📦 v0.24.0 via 🐍 v3.11.1
❯ cat reqs.txt
ghostscript==0.7
aiohttp==3.8.3
crpytography==0.1
cryptography==3.3.1
cryptography==38.0.4
pillow==3.4.2 …
```

fix: duplicate PR comments are possible

---

docs/sync/integrations_overview.md

docs: fix support link

---

Dockerfile
scripts/docker_tests.sh

Some tools get installed and used based on a home directory. This can cause trouble when using a container started from this image with a UID:GID that does not map to a user/group account in the container. Examples include:
* The install directory is `/root` and the container user has no access
* The tool relies on a `$HOME` directory, which may not exist
* https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15
The following tools are susceptible to this issue and therefore have been provided with explicit install/home directories that allow them to be globally accessible:
* Corepack, Yarn, and pnpm
* Rust, Cargo, and rustup
* Gradle
This issue was first discovered by @marvin-hansen and documented here: …

fix: container tools broken when home-less

---

.github/workflows/auto_updates.yml
.github/workflows/preview.yml
.github/workflows/release.yml
.github/workflows/test.yml
CONTRIBUTING.md
Dockerfile
Dockerfile.slim
README.md
poetry.lock
pyproject.toml
src/phylum/ci/ci_azure.py
src/phylum/ci/ci_base.py
src/phylum/ci/ci_bitbucket.py
src/phylum/ci/ci_github.py
src/phylum/ci/ci_gitlab.py
src/phylum/ci/ci_precommit.py
src/phylum/ci/cli.py
src/phylum/ci/common.py
src/phylum/ci/git.py
src/phylum/ci/lockfile.py
src/phylum/console.py
src/phylum/github.py
src/phylum/init/cli.py
src/phylum/logger.py
tests/conftest.py
tests/unit/test_package_metadata.py
tox.ini

This change coincides with the release of Python 3.12, which happened
02 OCT 2023. Anyone tracking this repository and this change should
update their use of pyenv locally, to include py3.12.x
Changes made to add Python 3.12 support include:
* Update the Docker base image version
* Update the CONTRIBUTING documentation
* Update the testing environments in `tox`, workflows, and unit tests
* Update `pyproject.toml` and generate an updated `poetry.lock` lockfile
* The existing `poetry-core` specified minimum requirement still works
Changes made to remove Python 3.8 support include:
* Update `pyproject.toml` and regenerate `poetry.lock`
* Upgrade target version for QA tools
* Use the new `str.removeprefix` and `str.removesuffix` methods
* Use `pyupgrade` to automatically update code
* Add a …

feat!: add Python 3.12 support and drop Python 3.8 support

---

.phylum_project
src/phylum/ci/ci_base.py
src/phylum/ci/ci_precommit.py
src/phylum/ci/cli.py
src/phylum/ci/common.py
src/phylum/ci/depfile.py
src/phylum/constants.py
src/phylum/exts/ci/main.ts
tests/unit/test_depfile_parse.py
tests/unit/test_depfileentry.py
tests/unit/test_lockfile_parse.py

The Phylum CLI v6.0.0 release will introduce a number of breaking
changes. This PR accounts for those changes with these actions:
* Change `find-lockable-files` command to `find-dependency-files`
* Change `--lockfile-type` arguments to `--type`
* Change `lockfiles` key in `phylum status --json` output to
`dependency_files`
* Change custom `ci` extension to match the extension API updates
* Change `analyze` packages type to `PackageWithOrigin`
* Rename `PackageDescriptor` dataclass to `Package`
* Make `lockfile` field mandatory
* Update tests
This change also takes the opportunity to make more breaking changes
by updating the remaining "lockfile" language with these actions:
* Rename `--lockfile` argument in `phylum-ci` script to `--depfile`
* Change short option from `-l` to `-d`
* Rename …

chore!: account for breaking Phylum CLI changes

---

.pre-commit-config.yaml
pyproject.toml
src/phylum/ci/common.py
src/phylum/ci/depfile.py

https://github.com/astral-sh/ruff/releases/tag/v0.1.12
https://github.com/astral-sh/ruff/releases/tag/v0.1.13

chore: update for the ruff v0.1.12 and v0.1.13 releases

---

.github/workflows/release.yml

* This is the third step in a three-step process
* The first step was https://github.com/phylum-dev/phylum-ci/pull/395
* The second step was https://github.com/phylum-dev/documentation/pull/110

ci: add documentation update trigger to release workflow

---

.pre-commit-config.yaml
tests/conftest.py

Reference: https://github.com/astral-sh/ruff/releases/tag/0.6.0

chore: update for the `ruff` v0.6.0 release

---

docs/integrations/gitlab_ci.md
src/phylum/ci/ci_base.py
src/phylum/ci/ci_gitlab.py
src/phylum/ci/cli.py

This change updates the GitLab integration to allow for tag pipelines. It also adds a prerequisite check to ensure that *only* explicitly supported pipeline types are used to trigger the integration. This now includes tag, branch, and merge request pipelines. Tag pipelines work the same way as branch pipelines run against the default branch: *all* dependencies are included in the analysis.
In the course of testing this change, a bug was discovered and fixed. It was possible for an included manifest to force analysis *before* there was a chance to set the `all_deps` property, causing tag or branch pipelines running on the default branch to analyze only new deps instead of all of them.
Specific changes made include:
* Ensure *all* dependencies are analyzed for tag pipelines and branch …

feat: support tag pipelines in GitLab integration
